### ISSUE TITLE
bug in the cron job

### ISSUE THREAD

**Issue by mattpannella** [openfpga-cores-inventory/analogue-pocket#3]
i noticed this a couple times before, and maybe it's not a big deal since it always corrects itself
but it seems like every once and a while some logic in the cron action for updating cores.yaml breaks and it updates a core to a previous version and then 15min later when the cron kicks in again, it fixes it and goes back to the latest version again

see commits:
156d0d526f34112912184625299f8cfc1a14a922
and
64ef9b33dcbdee78ff36d3859efea691350297ce

**Comment by joshcampbell191** [comment]
I'm going to close this for now as I haven't seen it happen since refactoring the cron script.
