### ISSUE TITLE
new repo for pram0d

### ISSUE THREAD

**Issue by mattpannella** [openfpga-cores-inventory/analogue-pocket#511]
https://github.com/Coin-OpCollection/Distribution-OpenFPGA

they're moving pram0ds cores to this repo and there's also 2 new ones from atract17

I figured I'd just make an issue because we should remove the old pram0ds ones first to avoid duplicates

but also, will have cores from multiple authors on one repo cause any issues?

**Comment by joshcampbell191** [comment]
I'll remove the old pram0d cores as there's currently an issue when updating the repository. The new one doesn't seem to contain a zip or anything.

**Comment by joshcampbell191** [comment]
Closed as per: https://github.com/openfpga-cores-inventory/analogue-pocket/pull/518
