### ISSUE TITLE
[New Core]: MyC64

### ISSUE THREAD

**Issue by markus-zzz** [openfpga-cores-inventory/analogue-pocket#633]
### Core Author username

markus-zzz

### Core .yml snippet

```yml
display_name: markus-zzz MyC64
repository: myc64-pocket
```

**Comment by markus-zzz** [comment]
Thanks @joshcampbell191 I have put together a small script (yet to be commited once confirmed that it is ok) to automate this process for me. A MyC64-Pocket.zip is now attached to the release.

**Comment by joshcampbell191** [comment]
@markus-zzz 

Thanks for including a zip containing the core files and folders.

It would appear that the 'assets' and 'platforms' folders were created in the wrong casing. Please rename these (**A**ssets and **P**latforms) to match those expected by Analogue OS and re-upload the asset.

**Comment by markus-zzz** [comment]
@joshcampbell191 

zip-archive updated

**Comment by dukestah** [comment]
Many thanks for this project, I'm more than happy to see the C64 coming to the Pocket!
